all :	fctNotes.o  notes.o
	gcc -o notes fctNotes.o  notes.o 
	
notes.o:	notes.c
	gcc -c -Wall -ansi -pedantic notes.c -o notes.o
	
fctNotes.o:	fctNotes.c
	gcc -c -Wall -ansi -pedantic fctNotes.c -o fctNotes.o
